
name: DemoApp PlayStore Release

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build APK and Create release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Update version in YAML
      run: sed -i 's/99.99.99+99/5.0.0/g' pubspec.yaml
#         run: sed -i 's/99.99.99+99/${{ 5 }}+${{ github.run_number }}/g' pubspec.yaml
    - name: Update KeyStore password in gradle properties
      run: sed -i 's/#{KEYSTORE_PASS}#/${{ secrets.KEYSTORE_PASS }}/g' android/app/key.properties
    - name: Update KeyStore key password in gradle properties
      run: sed -i 's/#{KEYSTORE_KEY_PASS}#/${{ secrets.KEYSTORE_KEY_PASS }}/g' android/app/key.properties
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.17.0'
    - run: flutter upgrade    
    - run: flutter pub get
#     - run: flutter build apk --release --split-per-abi
    - run: flutter build appbundle
#     - name: Create a Release in GitHub
#       uses: ncipollo/release-action@v1
#       with:
#         env:GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         env:token: ${{ secrets.GITHUB_TOKEN }}
#         artifacts: "build/app/outputs/apk/release/*.apk,build/app/outputs/bundle/release/app-release.aab"
#         token: ${{ secrets.GH_TOKEN }}
#         tag: ${{ steps.version.outputs.content }}
#         commit: ${{ github.sha }}
    - name: Upload app bundle
      uses: actions/upload-artifact@v2
      with:
        name: appbundle
        path: build/app/outputs/bundle/release/app-release.aab
  release:
    name: Release app to internal track
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Get appbundle from artifacts
      uses: actions/download-artifact@v2
      with:
        name: appbundle
    - name: Release app to internal track
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.PLAYSTORE_ACCOUNT_KEY }}
        packageName: com.fluttercicddemo
        releaseFile: app-release.aab
        track: internal
        whatsNewDirectory: distribution/whatsnew
